/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gt.examen.utils;

import com.gt.examen.dtos.EmailParameters;

/**
 *
 * @author Diego_MF
 */
public class CorreoElectronico {

    public String correoData(EmailParameters emailParameters) {

        String correo = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n"
                + "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\" style=\"width:100%;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;padding:0;Margin:0\">\n"
                + " <head>\n"
                + "  <meta charset=\"UTF-8\">\n"
                + "  <meta content=\"width=device-width, initial-scale=1\" name=\"viewport\">\n"
                + "  <meta name=\"x-apple-disable-message-reformatting\">\n"
                + "  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
                + "  <meta content=\"telephone=no\" name=\"format-detection\">\n"
                + "  <title>New message</title>\n"
                + "  <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700,700i\" rel=\"stylesheet\"><!--<![endif]-->\n"
                + "  <style type=\"text/css\">\n"
                + "#outlook a {\n"
                + "	padding:0;\n"
                + "}\n"
                + ".ExternalClass {\n"
                + "	width:100%;\n"
                + "}\n"
                + ".ExternalClass,\n"
                + ".ExternalClass p,\n"
                + ".ExternalClass span,\n"
                + ".ExternalClass font,\n"
                + ".ExternalClass td,\n"
                + ".ExternalClass div {\n"
                + "	line-height:100%;\n"
                + "}\n"
                + ".es-button {\n"
                + "	mso-style-priority:100!important;\n"
                + "	text-decoration:none!important;\n"
                + "}\n"
                + "a[x-apple-data-detectors] {\n"
                + "	color:inherit!important;\n"
                + "	text-decoration:none!important;\n"
                + "	font-size:inherit!important;\n"
                + "	font-family:inherit!important;\n"
                + "	font-weight:inherit!important;\n"
                + "	line-height:inherit!important;\n"
                + "}\n"
                + ".es-desk-hidden {\n"
                + "	display:none;\n"
                + "	float:left;\n"
                + "	overflow:hidden;\n"
                + "	width:0;\n"
                + "	max-height:0;\n"
                + "	line-height:0;\n"
                + "	mso-hide:all;\n"
                + "}\n"
                + "[data-ogsb] .es-button {\n"
                + "	border-width:0!important;\n"
                + "	padding:15px 25px 15px 25px!important;\n"
                + "}\n"
                + "@media only screen and (max-width:600px) {p, ul li, ol li, a { line-height:150%!important } h1, h2, h3, h1 a, h2 a, h3 a { line-height:120%!important } h1 { font-size:30px!important; text-align:center } h2 { font-size:26px!important; text-align:center } h3 { font-size:20px!important; text-align:center } .es-header-body h1 a, .es-content-body h1 a, .es-footer-body h1 a { font-size:30px!important } .es-header-body h2 a, .es-content-body h2 a, .es-footer-body h2 a { font-size:26px!important } .es-header-body h3 a, .es-content-body h3 a, .es-footer-body h3 a { font-size:20px!important } .es-menu td a { font-size:16px!important } .es-header-body p, .es-header-body ul li, .es-header-body ol li, .es-header-body a { font-size:16px!important } .es-content-body p, .es-content-body ul li, .es-content-body ol li, .es-content-body a { font-size:16px!important } .es-footer-body p, .es-footer-body ul li, .es-footer-body ol li, .es-footer-body a { font-size:16px!important } .es-infoblock p, .es-infoblock ul li, .es-infoblock ol li, .es-infoblock a { font-size:12px!important } *[class=\"gmail-fix\"] { display:none!important } .es-m-txt-c, .es-m-txt-c h1, .es-m-txt-c h2, .es-m-txt-c h3 { text-align:center!important } .es-m-txt-r, .es-m-txt-r h1, .es-m-txt-r h2, .es-m-txt-r h3 { text-align:right!important } .es-m-txt-l, .es-m-txt-l h1, .es-m-txt-l h2, .es-m-txt-l h3 { text-align:left!important } .es-m-txt-r img, .es-m-txt-c img, .es-m-txt-l img { display:inline!important } .es-button-border { display:inline-block!important } a.es-button, button.es-button { font-size:20px!important; display:inline-block!important; border-width:15px 25px 15px 25px!important } .es-btn-fw { border-width:10px 0px!important; text-align:center!important } .es-adaptive table, .es-btn-fw, .es-btn-fw-brdr, .es-left, .es-right { width:100%!important } .es-content table, .es-header table, .es-footer table, .es-content, .es-footer, .es-header { width:100%!important; max-width:600px!important } .es-adapt-td { display:block!important; width:100%!important } .adapt-img { width:100%!important; height:auto!important } .es-m-p0 { padding:0px!important } .es-m-p0r { padding-right:0px!important } .es-m-p0l { padding-left:0px!important } .es-m-p0t { padding-top:0px!important } .es-m-p0b { padding-bottom:0!important } .es-m-p20b { padding-bottom:20px!important } .es-mobile-hidden, .es-hidden { display:none!important } tr.es-desk-hidden, td.es-desk-hidden, table.es-desk-hidden { width:auto!important; overflow:visible!important; float:none!important; max-height:inherit!important; line-height:inherit!important } tr.es-desk-hidden { display:table-row!important } table.es-desk-hidden { display:table!important } td.es-desk-menu-hidden { display:table-cell!important } .es-menu td { width:1%!important } table.es-table-not-adapt, .esd-block-html table { width:auto!important } table.es-social { display:inline-block!important } table.es-social td { display:inline-block!important } .es-desk-hidden { display:table-row!important; width:auto!important; overflow:visible!important; max-height:inherit!important } }\n"
                + "</style>\n"
                + " </head>\n"
                + " <body style=\"width:100%;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;font-family:'open sans', 'helvetica neue', helvetica, arial, sans-serif;padding:0;Margin:0\">\n"
                + "  <div class=\"es-wrapper-color\" style=\"background-color:#F6F6F6\">\n"
                + "   <table class=\"es-wrapper\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;padding:0;Margin:0;width:100%;height:100%;background-repeat:repeat;background-position:center top;background-color:#F6F6F6\">\n"
                + "     <tr style=\"border-collapse:collapse\">\n"
                + "      <td valign=\"top\" style=\"padding:0;Margin:0\">\n"
                + "       <table class=\"es-header\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%;background-color:transparent;background-repeat:repeat;background-position:center top\">\n"
                + "         <tr style=\"border-collapse:collapse\">\n"
                + "          <td style=\"padding:0;Margin:0;background-image:url(https://yhwdeu.stripocdn.email/content/guids/CABINET_729b6a94015d410538fa6f6810b21b85/images/9701519718227204.jpg);background-position:center top;background-repeat:no-repeat;background-size:cover\" bgcolor=\"#3d4c6b\" align=\"center\" background=\"https://yhwdeu.stripocdn.email/content/guids/CABINET_729b6a94015d410538fa6f6810b21b85/images/9701519718227204.jpg\">\n"
                + "           <table class=\"es-header-body\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:transparent;width:640px\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\n"
                + "             <tr style=\"border-collapse:collapse\">\n"
                + "              <td align=\"left\" style=\"padding:0;Margin:0;padding-top:10px;padding-left:20px;padding-right:20px\">\n"
                + "               <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\n"
                + "                 <tr style=\"border-collapse:collapse\">\n"
                + "                  <td valign=\"top\" align=\"center\" style=\"padding:0;Margin:0;width:600px\">\n"
                + "                   <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" role=\"presentation\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\n"
                + "                     <tr style=\"border-collapse:collapse\">\n"
                + "                      <td align=\"center\" style=\"padding:0;Margin:0;padding-top:40px;padding-bottom:40px;font-size:0\"><a href=\"\" target=\"_blank\" style=\"-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:none;color:#B7BDC9;font-size:20px\"><img src=\"https://yhwdeu.stripocdn.email/content/guids/CABINET_729b6a94015d410538fa6f6810b21b85/images/90451519716512050.png\" style=\"display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic\" alt=\"Logo\" title=\"Logo\" width=\"50\"></a></td>\n"
                + "                     </tr>\n"
                + "                     <tr style=\"border-collapse:collapse\">\n"
                + "                      <td align=\"center\" style=\"padding:0;Margin:0;padding-top:10px;font-size:0\">\n"
                + "                        <a target=\"_blank\" href=\"\" style=\"-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:none;color:#B7BDC9;font-size:20px\">\n"
                + "                        <img src=\"https://app1.mcd.gob.gt/Resources/umglogo.png\" width=\"200\"  style=\"display: block; border: 0px;\" >		\n"
                + "                        </a></td>\n"
                + "                     </tr>\n"
                + "                   </table></td>\n"
                + "                 </tr>\n"
                + "               </table></td>\n"
                + "             </tr>\n"
                + "           </table></td>\n"
                + "         </tr>\n"
                + "       </table>\n"
                + "       <table class=\"es-content\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%\">\n"
                + "       \n"
                + "          <tr style=\"border-collapse:collapse\">\n"
                + "            <td align=\"center\" style=\"padding:0;Margin:0\">\n"
                + "            <table class=\"es-content-body\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:transparent;width:640px\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\n"
                + "              <tr style=\"border-collapse:collapse\">\n"
                + "                <td align=\"left\" style=\"padding:0;Margin:0;padding-left:20px;padding-right:20px\">\n"
                + "                <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\n"
                + "                  <tr style=\"border-collapse:collapse\">\n"
                + "                    <td valign=\"top\" align=\"center\" style=\"padding:0;Margin:0;width:600px\">\n"
                + "                    <table style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:separate;border-spacing:0px;border-radius:3px;background-color:#ffffff\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#ffffff\" role=\"presentation\">\n"
                + "                      <tr style=\"border-collapse:collapse\">\n"
                + "                        <td align=\"center\" style=\"Margin:0;padding-bottom:5px;padding-left:20px;padding-right:20px;padding-top:25px\">\n"
                + "                          <h2 style=\"Margin:0;line-height:34px;mso-line-height-rule:exactly;font-family:'open sans', 'helvetica neue', helvetica, arial, sans-serif;font-size:20px;font-style:normal;font-weight:bold;color:#444444 ; margin: 0; text-align:justify;\">\n"
                + "                            <font style=\"vertical-align:justify\"><font style=\"vertical-align:justify\">Estimado Usuario </font></font>\n"
                + "                            <br>\n"
                + "                          </h2>\n"
                + "                        </td>\n"
                + "                      </tr>\n"
                + "                      <tr style=\"border-collapse:collapse\">\n"
                + "                        <td align=\"center\" style=\"Margin:0;padding-top:10px;padding-bottom:15px;padding-left:20px;padding-right:20px\"><p style=\"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:'open sans', 'helvetica neue', helvetica, arial, sans-serif;line-height:24px;color:#999999;font-size:16px ; margin: 0; text-align:justify;\"><span class=\"product-description\"><font style=\"vertical-align:inherit\">\n"
                + "                          <font style=\"vertical-align:inherit\">Por este medio se le hace de su conocimiento la siguiente información : </font></font></span></p></td>\n"
                + "                      </tr>\n"
                + "                    </table></td>\n"
                + "                  </tr>\n"
                + "                </table></td>\n"
                + "              </tr>\n"
                + "            </table></td>\n"
                + "          </tr>\n"
                + "       </table>\n"
                + "\n"
                + "       \n"
                + "       <table class=\"es-content\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%\">\n"
                + "         <tr style=\"border-collapse:collapse\">\n"
                + "          <td align=\"center\" style=\"padding:0;Margin:0\">\n"
                + "           <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"max-width: 630px;\">\n"
                + "            <tr>\n"
                + "                <td></td>\n"
                + "                <td style=\"padding: 10px; width: 650px; vertical-align: top;\">\n"
                + "                    <table\n"
                + "                        style=\"padding: 10px; width: 100%; font-family: Arial, Helvetica, sans-serif; background-color: #ffffff; border: 0;\">\n"
                + "                        <tbody>\n"
                + "                                                          \n"
                + "                            <tr>\n"
                + "                                <td style=\"padding: 4 2; color: #ffffff; font-size: 15px; text-align: center; background-color: #09254D;\" colspan=\"3\">\n"
                + "                                    <strong> Información</strong>\n"
                + "                                </td>\n"
                + "                            </tr>\n"
                + "                \n"
                + "                            <tr style='height:35.25pt'>\n"
                + "                                <td width=100 valign=top>\n"
                + "                                    <p class=MsoNormal><b><span lang=ES style='font-family:\"Arial\",sans-serif'>Nombre :</span></b></p>\n"
                + "                                </td>\n"
                + "                                <td width=332 valign=top>\n"
                + "                                    <p class=MsoNormal align=center style='text-align:center'><span lang=ES style='font-family:\"Arial\",sans-serif'>"+emailParameters.getNombreRemitente()+"</span></p>\n"
                + "                                </td>\n"
                + "                            </tr>\n"
                + "                            <tr style='height:35.25pt'>\n"
                + "                                <td width=300 valign=top style=\"overflow-x:auto;\">\n"
                + "                                    <p class=MsoNormal><b><span lang=ES style='font-family:\"Arial\",sans-serif'>Puesto :</span></b></p>\n"
                + "                                </td>\n"
                + "                                <td width=334 valign=top style=\"overflow-x:auto;\">\n"
                + "                                    <p class=MsoNormal align=center style='text-align:center'><span lang=ES style='font-family:\"Arial\",sans-serif'>"+emailParameters.getPuesto()+"</span></p>\n"
                + "                                </td>\n"
                + "                            </tr>\n"
                + "                            <tr style='height:35.25pt'>\n"
                + "                                <td width=300 valign=top  style=\"overflow-x:auto;\">\n"
                + "                                    <p class=MsoNormal><b><span lang=ES style='font-family:\"Arial\",sans-serif'>Número de Telefono :</span></b></p>\n"
                + "                                </td>\n"
                + "                                <td width=322 valign=top style=\"overflow-x:auto;\">\n"
                + "                                    <p class=MsoNormal align=center style='text-align:center'><span lang=ES style='font-family:\"Arial\",sans-serif'>"+emailParameters.getTelefono()+"</span></p>\n"
                + "                                </td>\n"
                + "                            </tr>\n"
                + "                            <tr style='height:35.25pt'>\n"
                + "                              <td width=300 valign=top  style=\"overflow-x:auto;\">\n"
                + "                                  <p class=MsoNormal><b><span lang=ES style='font-family:\"Arial\",sans-serif'>Cuerpo Correo:</span></b></p>\n"
                + "                              </td>\n"
                + "                              <td width=322 valign=top style=\"overflow-x:auto;\">\n"
                + "                                  <p class=MsoNormal align=center style='text-align:center'><span lang=ES style='font-family:\"Arial\",sans-serif'>"+emailParameters.getCuerpoMensaje()+"</span></p>\n"
                + "                              </td>\n"
                + "                          </tr>\n"
                + "\n"
                + "                        </tbody>\n"
                + "                    </table>\n"
                + "          </td>\n"
                + "         </tr>\n"
                + "       </table>\n"
                + "\n"
                + "       <table class=\"es-content\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%\">\n"
                + "         <tr style=\"border-collapse:collapse\">\n"
                + "          <td style=\"padding:0;Margin:0;background-color:#f6f6f6\" bgcolor=\"#f6f6f6\" align=\"center\">\n"
                + "           <table class=\"es-content-body\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:transparent;width:640px\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\n"
                + "             <tr style=\"border-collapse:collapse\">\n"
                + "              <td align=\"left\" style=\"Margin:0;padding-left:20px;padding-right:20px;padding-top:30px;padding-bottom:30px\">\n"
                + "               <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\n"
                + "                 <tr style=\"border-collapse:collapse\">\n"
                + "                 </tr>\n"
                + "               </table></td>\n"
                + "             </tr>\n"
                + "           </table></td>\n"
                + "         </tr>\n"
                + "       </table></td>\n"
                + "     </tr>\n"
                + "   </table>\n"
                + "  </div>\n"
                + " </body>\n"
                + "</html>";
        
        return correo;

    }

}
